version: 2
updates:
    - package-ecosystem: gradle
      directory: /
      schedule:
          interval: weekly
      open-pull-requests-limit: 5
      groups:
          java-build-dependencies:
              patterns:
                  - "*"

    - package-ecosystem: github-actions
      directory: /
      schedule:
          interval: weekly
      open-pull-requests-limit: 5
      groups:
          github-actions:
              patterns:
                  - "*"
