pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = 'NeoForged'
            url = 'https://maven.neoforged.net/releases'
        }
        maven {
            name = 'Forge'
            url = 'https://maven.minecraftforge.net/'
        }
        mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.name = 'thread'

include 'common', 'minecraft-26.2', 'fabric', 'neoforge', 'forge', 'universal'
