pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = 'NeoForged'
            url = 'https://maven.neoforged.net/releases'
        }
        maven {
            name = 'Forge'
            url = 'https://maven.minecraftforge.net/'
        }
        mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.name = 'thread'

apply from: 'gradle/version-matrix.gradle'

include 'common'

threadBuildMatrix.versions.keySet().each { minecraftVersion ->
    def minecraftPath = ":minecraft:${minecraftVersion}"
    include minecraftPath
    project(minecraftPath).projectDir = file("minecraft/${minecraftVersion}")

    threadBuildMatrix.loaders.each { loader ->
        def loaderPath = ":loaders:${loader}:${minecraftVersion}"
        include loaderPath
        project(loaderPath).projectDir = file("loaders/${loader}/${minecraftVersion}")
    }
}
