modLoader="javafml"
loaderVersion="[${forgeLoaderMajor},)"
license="All Rights Reserved"
clientSideOnly=true

[[mods]]
modId="thread_forge_gametest"
version="1.2.3"
displayName="Thread Forge Packaged Tests"

[[dependencies.thread_forge_gametest]]
modId="thread"
mandatory=true
versionRange="[1.0.0,)"
ordering="AFTER"
side="CLIENT"
