base {
    archivesName = 'thread-common'
}

dependencies {
    compileOnly "com.google.code.gson:gson:${rootProject.gson_version}"
    testImplementation "com.google.code.gson:gson:${rootProject.gson_version}"
}

tasks.named('test') {
    systemProperty 'thread.rootDir', rootProject.projectDir.absolutePath
}
