modLoader="javafml"
loaderVersion="[1,)"
license="All Rights Reserved"

[[mods]]
modId="thread_neoforge_gametest"
version="1.2.3"
displayName="Thread NeoForge Packaged Tests"

[[dependencies.thread_neoforge_gametest]]
modId="thread"
type="required"
versionRange="[1.0.0,)"
ordering="AFTER"
side="CLIENT"
